name: Build Containers for Staging & Push to Dockerhub

on:
  pull_request:
    branches:
      - staging

jobs:
  Vitest:
    name: Running unit and integration tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  Cypress:
    name: Running End To End Tests
    runs-on: ubuntu-latest
    needs: Test1
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v4
      - name: Cypress run
        with:
          browser: chrome
          build: npm run build
          start: npm run preview
          wait-on: "http://localhost:4173"
